### ISSUE TITLE
Fails to install -- even with a Python 3.9 and MacOS

### ISSUE THREAD

**Issue by worldOfA** [kargaranamir/visual-clutter#1]
Hi,

**EDIT:** Upon using Python 3.8, we can work around this issue.

Can you kindly help me with this? The pip install continues to fail with a huge error trace -- pasted below, some parts of the stack trace:

 13 warnings and 1 error generated.
    4 warnings generated.
    error: Command "gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/Users/ack/PycharmProjects/tryag/venv/lib/python3.9/site-packages/numpy/core/include -I/Users/ack/PycharmProjects/tryag/venv/lib/python3.9/site-packages/numpy/core/include -Ibuild/src.macosx-10.9-x86_64-3.9/numpy/distutils/include -I/Users/ack/PycharmProjects/tryag/venv/include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c skimage/restoration/_unwrap_2d.c -o build/temp.macosx-10.9-x86_64-cpython-39/skimage/restoration/_unwrap_2d.o -MMD -MF build/temp.macosx-10.9-x86_64-cpython-39/skimage/restoration/_unwrap_2d.o.d -msse -msse2 -msse3" failed with exit status 1
    
    ########### EXT COMPILER OPTIMIZATION ###########
    Platform      :
      Architecture: x64
      Compiler    : gcc
    
    CPU baseline  :
      Requested   : 'min'
      Enabled     : SSE SSE2 SSE3
      Flags       : -msse -msse2 -msse3
      Extra checks: none
    
    CPU dispatch  :
      Requested   : 'max -xop -fma4'
      Enabled     : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_KNL AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
      Generated   : none
    CCompilerOpt._cache_write[796] : write cache to path -> /private/var/folders/tj/v_1kwkrx3c50nvjtc6x2n5ym0000gn/T/pip-install-y0bh79lz/scikit-image_4b398cfce52647b489ac9d7dd65c6174/build/temp.macosx-10.9-x86_64-cpython-39/ccompiler_opt_cache_ext.py

Best!

**Comment by kargaranamir** [comment]
Hi, Thanks for the report. 

Can you install pyrtools library?

```
pip install pyrtools
```

**Comment by kargaranamir** [comment]
It seems the error is related to the skimage package. However, I first want to make sure you can install pyrtools.
Probably I need to check which version of skimage is ok with both my code and python 3.9.

**Comment by worldOfA** [comment]
Thanks for the prompt reply! it seems pyrtools can be installed:
Requirement already satisfied: pyrtools in ./venv/lib/python3.8/site-packages (1.0.1)

Indeed, it does seem like an incompatibility between the skimage image and this library. However, since it works on python 3.8, we could close the issue, if you'd like for now.

Forgive, this unrelated question: the weighted FC score on a 206 KB jpg file takes around : 176.219 seconds to compute. While I know FC isn't exactly known to be a computationally fast metric to calculate (AIM's paper: 11.165 with. +- st dev). I was wondering if this implementation differs from the one you provide in Aalto's AIM m8?

**Comment by kargaranamir** [comment]
Sure, thanks. 

The AIM paper (Let's say AIM1) does not include the current AIM (Let's say AIM2) m8 metric. The implementation of this repository is equivalent to the AIM2 m8 metric. I first put it here and then add it to the current AIM. You can check the `m8_time` in this [sheet](https://github.com/aalto-ui/aim/blob/aim2/backend/data/evaluations/ALEXA_500/results.csv) for details on the speed of the m8 metric.

Improving the speed of this implementation would be possible if the [rotation](https://github.com/kargaranamir/visual-clutter/blob/7fd7f31b919857273d759b2462d860614204a8f4/visual_clutter/utils.py#L376) function were optimized (This is the major bottleneck). Our current implementation uses the skimage rotation function, chosen for its nearest match to the interpolation of the MATLAB rotation function.

**Comment by kargaranamir** [comment]
For the computing FC you just need to do this:

```
from visual_clutter import Vlc

# make visual clutter object and load test map and set parameters
clt = Vlc('./tests/test.jpg', numlevels=3, contrast_filt_sigma=1, contrast_pool_sigma=3, color_pool_sigma=3)

# get Feature Congestion clutter of a test map:
clutter_scalar_fc, clutter_map_fc = clt.getClutter_FC(p=1, pix=1)
```

Are you using a different code?

**Comment by worldOfA** [comment]
<img width="965" alt="Screenshot 2023-03-27 at 2 36 49 PM" src="https://user-images.githubusercontent.com/87204831/227942766-8e92fba9-54e5-44d6-9aac-22046a60cbd5.png">

Yes, I am attaching code for reference!
I didn't need the clusters in .png, so I made minor modifications.

**Comment by worldOfA** [comment]
<img width="965" alt="Screenshot 2023-03-27 at 2 36 49 PM" src="https://user-images.githubusercontent.com/87204831/227942766-8e92fba9-54e5-44d6-9aac-22046a60cbd5.png">

Yes, I am attaching code for reference!

**Comment by kargaranamir** [comment]
Hi @worldOfA,

Good news! I've fixed the problem, and I'm wondering if you're still using the project.

I've updated the requirements.txt file to allow for newer versions of dependencies. This means our [demo](https://huggingface.co/spaces/kargaranamir/visual-clutter), which was previously not working, is now up and running again.

Thank you for bringing this to my attention.
